trigger:
  - main

variables:
  - name: NodeVersion
    value: "18"
  - name: Tags
    value: |
      $(Build.BuildNumber)
      node-$(NodeVersion)
  - name: Repository
    value: davidullrich/azurepipelineagent

jobs:
- job: BuildAndPublish
  displayName: Build and Publish Image
    
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: DockerHubConnection

  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      dockerfile: $(Build.SourcesDirectory)/dockerfile
      repository: $(Repository)
      addBaseImageData: false
      addPipelineData: false
      arguments: --build-arg NODE_VERSION=$(NodeVersion)
      tags: $(Tags)

  - task: Docker@2
    displayName: Push Image
    inputs:
      command: push
      repository: $(Repository)
      tags: $(Tags)

  - task: Docker@2
    displayName: Logout
    inputs:
      command: logout
      containerRegistry: DockerHubConnection
