trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

jobs:
- job: BuildAndPublish
  displayName: Build and Publish Image
    
  pool:
    vmImage: ubuntu-latest
  
  steps:
  - task: Docker@2
    displayName: Docker Login
    inputs:
      command: login
      containerRegistry: DockerHubConnection

  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      dockerfile: "$(Build.SourcesDirectory)/dockerfile"
      repository: "davidullrich/azurepipelineagent"
      tags: |
        $(tag)
        latest

  - task: Docker@2
    displayName: Push Image
    inputs:
      command: push
      repository: "davidullrich/azurepipelineagent"
      tags: |
        $(tag)
        latest
