trigger:
  - main

parameters:
  - name: ForcePushDockerImage
    displayName: Force push docker image
    type: boolean
    values:
      - true
      - false
    default: false

variables:
  - name: Repository
    value: davidullrich/azurepipelineagent
  - name: IsMainBranch
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - name: PushDockerImage
    value: ${{ 
        or( 
          eq(variables.IsMainBranch, 'true'),
          parameters.ForcePushDockerImage
        )
      }}

jobs:
- job: BuildAndPublish
  displayName: Build and Publish

  strategy:
    matrix:
      node20:
        NodeVersion: "20"
        Tags: |
          node-$(NodeVersion)
      node21:
        NodeVersion: "21"
        Tags: |
          node-$(NodeVersion)
          latest
  
  pool:
    name: "Self-hosted"
  
  container:
    image: davidullrich/azurepipelineagent:latest

  steps:
  - task: DockerInstaller@0
    displayName: Install Docker CLI
    inputs:
      dockerVersion: "24.0.7"

  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      dockerfile: $(Build.SourcesDirectory)/dockerfile
      repository: $(Repository)
      addBaseImageData: false
      addPipelineData: false
      arguments: --no-cache --build-arg NODE_VERSION=$(NodeVersion)
      tags: $(Tags)

  - ${{ if eq(variables.ForcePushDockerImage, 'true') }}:
    - task: Docker@2
      displayName: Login
      inputs:
        command: login
        containerRegistry: DockerHubConnection

    - task: Docker@2
      displayName: Push Image
      inputs:
        command: push
        repository: $(Repository)
        tags: $(Tags)

    - task: Docker@2
      displayName: Logout
      inputs:
        command: logout
        containerRegistry: DockerHubConnection
