trigger:
  - main

variables:
  - name: Repository
    value: davidullrich/azurepipelineagent

jobs:
- job: BuildAndPublish
  displayName: Build and Publish

  strategy:
    matrix:
      node20:
        NodeVersion: "20"
        Tags: |
          node-$(NodeVersion)
      node21:
        NodeVersion: "21"
        Tags: |
          node-$(NodeVersion)
          latest
  
  pool:
    name: "Self-hosted"
  
  container:
    image: davidullrich/azurepipelineagent:node-20

  steps:
  - task: DockerInstaller@0
    displayName: Install Docker CLI
    inputs:
      dockerVersion: "24.0.7"

  - task: Docker@2
    displayName: Login
    inputs:
      command: login
      containerRegistry: DockerHubConnection

  - task: Docker@2
    displayName: Build Image
    inputs:
      command: build
      dockerfile: $(Build.SourcesDirectory)/dockerfile
      repository: $(Repository)
      addBaseImageData: false
      addPipelineData: false
      arguments: --no-cache --build-arg NODE_VERSION=$(NodeVersion)
      tags: $(Tags)

  - task: Docker@2
    displayName: Push Image
    inputs:
      command: push
      repository: $(Repository)
      tags: $(Tags)

  - task: Docker@2
    displayName: Logout
    inputs:
      command: logout
      containerRegistry: DockerHubConnection
